name: 'reusable action'
description: 'testing purposes'
on:
  workflow_call:
    inputs:
      token:
        required: false

jobs:
  test-access:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo The username is ${{ inputs.token }}
