name: 'reusable action'
description: 'testing purposes'
on:
  workflow_call:
    secrets:
      access-token:
        description: 'A token passed from the caller workflow'
        required: true
jobs:
  pass-secret:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        env: 
          access-token: ${{ secrets.EB_TEST_CONTEXT_SECRET }}
        run: |
          if [[ true ]]; then echo $access-token; else exit 1; fi
        shell: bash
